export class TeamInfo
{
  teams = [
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Croatia",
        "altCityName": "Croatia",
        "teamName": "Team Croatia",
        "tricode": "CRO",
        "teamId": 70,
        "simpleName": "Croatia",
        "urlName": "croatia",
        "teamShortName": "Croatia",
        "confName": "summer",
        "divName": ""
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "China",
        "altCityName": "China",
        "teamName": "Team China",
        "tricode": "CHN",
        "teamId": 45,
        "simpleName": "China",
        "urlName": "china",
        "teamShortName": "China",
        "confName": "summer",
        "divName": ""
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Adelaide",
        "altCityName": "Adelaide",
        "teamName": "Adelaide 36ers",
        "tricode": "ADL",
        "teamId": 15019,
        "simpleName": "36ers",
        "urlName": "36ers",
        "teamShortName": "Adelaide",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Atlanta",
        "altCityName": "Atlanta",
        "teamName": "Atlanta Hawks",
        "tricode": "ATL",
        "teamId": 1610612737,
        "simpleName": "Hawks",
        "urlName": "hawks",
        "teamShortName": "Atlanta",
        "confName": "East",
        "divName": "Southeast",
        "primaryColor": "#E03A3E",
        "secondaryColor": "#C1D32F",
        "primaryLogoLocation": "assets/images/team_logos/hawks_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/hawks_secondary.png"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": true,
        "location": "Away",
        "altCityName": "Away",
        "teamName": "Away Away",
        "tricode": "AWY",
        "teamId": 1610616840,
        "simpleName": "Away",
        "urlName": "away",
        "teamShortName": "Away",
        "confName": "East",
        "divName": "East"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Beijing",
        "altCityName": "Beijing",
        "teamName": "Beijing Ducks",
        "tricode": "BJD",
        "teamId": 15021,
        "simpleName": "Ducks",
        "urlName": "ducks",
        "teamShortName": "Beijing",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Boston",
        "altCityName": "Boston",
        "teamName": "Boston Celtics",
        "tricode": "BOS",
        "teamId": 1610612738,
        "simpleName": "Celtics",
        "urlName": "celtics",
        "teamShortName": "Boston",
        "confName": "East",
        "divName": "Atlantic",
        "primaryColor": "#007A33",
        "secondaryColor": "#BA9653",
        "primaryLogoLocation": "assets/images/team_logos/celtics_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/celtics_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Brooklyn",
        "altCityName": "Brooklyn",
        "teamName": "Brooklyn Nets",
        "tricode": "BKN",
        "teamId": 1610612751,
        "simpleName": "Nets",
        "urlName": "nets",
        "teamShortName": "Brooklyn",
        "confName": "East",
        "divName": "Atlantic",
        "primaryColor": "#000000",
        "secondaryColor": "#FFFFFF",
        "primaryLogoLocation": "assets/images/team_logos/nets_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/nets_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Charlotte",
        "altCityName": "Charlotte",
        "teamName": "Charlotte Hornets",
        "tricode": "CHA",
        "teamId": 1610612766,
        "simpleName": "Hornets",
        "urlName": "hornets",
        "teamShortName": "Charlotte",
        "confName": "East",
        "divName": "Southeast",
        "primaryColor": "#1D1160",
        "secondaryColor": "#00788C",
        "primaryLogoLocation": "assets/images/team_logos/hornets_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/hornets_secondary.png"
    },
    {

        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Buenos Aires",
        "altCityName": "Buenos Aires",
        "teamName": "San Lorenzo de Almagro",
        "tricode": "SLA",
        "teamId": 12330,
        "simpleName": "San Lorenzo",
        "urlName": "san_lorenzo",
        "teamShortName": "San Lorenzo",
        "confName": "Intl",
        "divName": ""
    
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Chicago",
        "altCityName": "Chicago",
        "teamName": "Chicago Bulls",
        "tricode": "CHI",
        "teamId": 1610612741,
        "simpleName": "Bulls",
        "urlName": "bulls",
        "teamShortName": "Chicago",
        "confName": "East",
        "divName": "Central",
        "primaryColor": "#CE1141",
        "secondaryColor": "#000000",
        "primaryLogoLocation": "assets/images/team_logos/bulls_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/bulls_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Cleveland",
        "altCityName": "Cleveland",
        "teamName": "Cleveland Cavaliers",
        "tricode": "CLE",
        "teamId": 1610612739,
        "simpleName": "Cavaliers",
        "urlName": "cavaliers",
        "teamShortName": "Cleveland",
        "confName": "East",
        "divName": "Central",
        "primaryColor": "#860038",
        "secondaryColor": "#FDBB30",
        "primaryLogoLocation": "assets/images/team_logos/cavaliers_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/cavaliers_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Dallas",
        "altCityName": "Dallas",
        "teamName": "Dallas Mavericks",
        "tricode": "DAL",
        "teamId": 1610612742,
        "simpleName": "Mavericks",
        "urlName": "mavericks",
        "teamShortName": "Dallas",
        "confName": "West",
        "divName": "Southwest",
        "primaryColor": "#00538C",
        "secondaryColor": "#B8C4CA",
        "primaryLogoLocation": "assets/images/team_logos/mavericks_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/mavericks_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Denver",
        "altCityName": "Denver",
        "teamName": "Denver Nuggets",
        "tricode": "DEN",
        "teamId": 1610612743,
        "simpleName": "Nuggets",
        "urlName": "nuggets",
        "teamShortName": "Denver",
        "confName": "West",
        "divName": "Northwest",
        "primaryColor": "#0E2240",
        "secondaryColor": "#FEC524",
        "primaryLogoLocation": "assets/images/team_logos/nuggets_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/nuggets_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Detroit",
        "altCityName": "Detroit",
        "teamName": "Detroit Pistons",
        "tricode": "DET",
        "teamId": 1610612765,
        "simpleName": "Pistons",
        "urlName": "pistons",
        "teamShortName": "Detroit",
        "confName": "East",
        "divName": "Central",
        "primaryColor": "#C8102E",
        "secondaryColor": "#1D42BA",
        "primaryLogoLocation": "assets/images/team_logos/pistons_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/pistons_secondary.gif"
    },
    {

        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Franca",
        "altCityName": "Franca",
        "teamName": "SESI/Franca",
        "tricode": "FRA",
        "teamId": 12332,
        "simpleName": "Franca",
        "urlName": "franca",
        "teamShortName": "Franca",
        "confName": "Intl",
        "divName": ""
    
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Golden State",
        "altCityName": "Golden State",
        "teamName": "Golden State Warriors",
        "tricode": "GSW",
        "teamId": 1610612744,
        "simpleName": "Warriors",
        "urlName": "warriors",
        "teamShortName": "Golden State",
        "confName": "West",
        "divName": "Pacific",
        "primaryColor": "#1D428A",
        "secondaryColor": "#FFC72C",
        "primaryLogoLocation": "assets/images/team_logos/warriors_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/warriors_secondary.png"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Guangzhou",
        "altCityName": "Guangzhou",
        "teamName": "Guangzhou Long-Lions",
        "tricode": "GUA",
        "teamId": 15018,
        "simpleName": "Long-Lions",
        "urlName": "long-lions",
        "teamShortName": "Guangzhou",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Haifa",
        "altCityName": "Haifa",
        "teamName": "Haifa Maccabi Haifa",
        "tricode": "MAC",
        "teamId": 93,
        "simpleName": "Maccabi Haifa",
        "urlName": "maccabi_haifa",
        "teamShortName": "Maccabi Haifa",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": false,
        "isAllStar": true,
        "location": "Home",
        "altCityName": "Home",
        "teamName": "Home Home",
        "tricode": "HME",
        "teamId": 1610616839,
        "simpleName": "Home",
        "urlName": "home",
        "teamShortName": "Home",
        "confName": "East",
        "divName": "East"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Houston",
        "altCityName": "Houston",
        "teamName": "Houston Rockets",
        "tricode": "HOU",
        "teamId": 1610612745,
        "simpleName": "Rockets",
        "urlName": "rockets",
        "teamShortName": "Houston",
        "confName": "West",
        "divName": "Southwest",
        "primaryColor": "#CE1141",
        "secondaryColor": "#C4CED4",
        "primaryLogoLocation": "assets/images/team_logos/rockets_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/rockets_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Indiana",
        "altCityName": "Indiana",
        "teamName": "Indiana Pacers",
        "tricode": "IND",
        "teamId": 1610612754,
        "simpleName": "Pacers",
        "urlName": "pacers",
        "teamShortName": "Indiana",
        "confName": "East",
        "divName": "Central",
        "primaryColor": "#002D62",
        "secondaryColor": "#FDBB30",
        "primaryLogoLocation": "assets/images/team_logos/pacers_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/pacers_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "LA",
        "altCityName": "LA Clippers",
        "teamName": "LA Clippers",
        "tricode": "LAC",
        "teamId": 1610612746,
        "simpleName": "Clippers",
        "urlName": "clippers",
        "teamShortName": "LA Clippers",
        "confName": "West",
        "divName": "Pacific",
        "primaryColor": "#C8102E",
        "secondaryColor": "#1D428A",
        "primaryLogoLocation": "assets/images/team_logos/clippers_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/clippers_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Los Angeles",
        "altCityName": "Los Angeles Lakers",
        "teamName": "Los Angeles Lakers",
        "tricode": "LAL",
        "teamId": 1610612747,
        "simpleName": "Lakers",
        "urlName": "lakers",
        "teamShortName": "L.A. Lakers",
        "confName": "West",
        "divName": "Pacific",
        "primaryColor": "#552583",
        "secondaryColor": "#FDB927",
        "primaryLogoLocation": "assets/images/team_logos/lakers_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/lakers_secondary.png"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Melbourne",
        "altCityName": "Melbourne",
        "teamName": "Melbourne United",
        "tricode": "MEL",
        "teamId": 15016,
        "simpleName": "United",
        "urlName": "united",
        "teamShortName": "Melbourne",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Memphis",
        "altCityName": "Memphis",
        "teamName": "Memphis Grizzlies",
        "tricode": "MEM",
        "teamId": 1610612763,
        "simpleName": "Grizzlies",
        "urlName": "grizzlies",
        "teamShortName": "Memphis",
        "confName": "West",
        "divName": "Southwest",
        "primaryColor": "#5D76A9",
        "secondaryColor": "#12173F",
        "primaryLogoLocation": "assets/images/team_logos/grizzlies_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/grizzlies_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Miami",
        "altCityName": "Miami",
        "teamName": "Miami Heat",
        "tricode": "MIA",
        "teamId": 1610612748,
        "simpleName": "Heat",
        "urlName": "heat",
        "teamShortName": "Miami",
        "confName": "East",
        "divName": "Southeast",
        "primaryColor": "#98002E",
        "secondaryColor": "#F9A01B",
        "primaryLogoLocation": "assets/images/team_logos/heat_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/heat_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Milwaukee",
        "altCityName": "Milwaukee",
        "teamName": "Milwaukee Bucks",
        "tricode": "MIL",
        "teamId": 1610612749,
        "simpleName": "Bucks",
        "urlName": "bucks",
        "teamShortName": "Milwaukee",
        "confName": "East",
        "divName": "Central",
        "primaryColor": "#00471B",
        "secondaryColor": "#EEE1C6",
        "primaryLogoLocation": "assets/images/team_logos/bucks_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/bucks_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Minnesota",
        "altCityName": "Minnesota",
        "teamName": "Minnesota Timberwolves",
        "tricode": "MIN",
        "teamId": 1610612750,
        "simpleName": "Timberwolves",
        "urlName": "timberwolves",
        "teamShortName": "Minnesota",
        "confName": "West",
        "divName": "Northwest",
        "primaryColor": "#0C2340",
        "secondaryColor": "#9EA2A2",
        "primaryLogoLocation": "assets/images/team_logos/timberwolves_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/timberwolves_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "New Orleans",
        "altCityName": "New Orleans",
        "teamName": "New Orleans Pelicans",
        "tricode": "NOP",
        "teamId": 1610612740,
        "simpleName": "Pelicans",
        "urlName": "pelicans",
        "teamShortName": "New Orleans",
        "confName": "West",
        "divName": "Southwest",
        "primaryColor": "#0C2340",
        "secondaryColor": "#85714D",
        "primaryLogoLocation": "assets/images/team_logos/pelicans_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/pelicans_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "New York",
        "altCityName": "New York",
        "teamName": "New York Knicks",
        "tricode": "NYK",
        "teamId": 1610612752,
        "simpleName": "Knicks",
        "urlName": "knicks",
        "teamShortName": "New York",
        "confName": "East",
        "divName": "Atlantic",
        "primaryColor": "#006BB6",
        "secondaryColor": "#F58426",
        "primaryLogoLocation": "assets/images/team_logos/knicks_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/knicks_secondary.png"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "New Zealand",
        "altCityName": "New Zealand",
        "teamName": "New Zealand Breakers",
        "tricode": "NZB",
        "teamId": 15020,
        "simpleName": "Breakers",
        "urlName": "breakers",
        "teamShortName": "New Zealand",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Oklahoma City",
        "altCityName": "Oklahoma City",
        "teamName": "Oklahoma City Thunder",
        "tricode": "OKC",
        "teamId": 1610612760,
        "simpleName": "Thunder",
        "urlName": "thunder",
        "teamShortName": "Oklahoma City",
        "confName": "West",
        "divName": "Northwest",
        "primaryColor": "#007AC1",
        "secondaryColor": "#EF3B24",
        "primaryLogoLocation": "assets/images/team_logos/thunder_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/thunder_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Orlando",
        "altCityName": "Orlando",
        "teamName": "Orlando Magic",
        "tricode": "ORL",
        "teamId": 1610612753,
        "simpleName": "Magic",
        "urlName": "magic",
        "teamShortName": "Orlando",
        "confName": "East",
        "divName": "Southeast",
        "primaryColor": "#0077C0",
        "secondaryColor": "#C4CED4",
        "primaryLogoLocation": "assets/images/team_logos/magic_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/magic_secondary.png"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Perth",
        "altCityName": "Perth",
        "teamName": "Perth Wildcats",
        "tricode": "PER",
        "teamId": 104,
        "simpleName": "Wildcats",
        "urlName": "wildcats",
        "teamShortName": "Perth",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Philadelphia",
        "altCityName": "Philadelphia",
        "teamName": "Philadelphia 76ers",
        "tricode": "PHI",
        "teamId": 1610612755,
        "simpleName": "76ers",
        "urlName": "sixers",
        "teamShortName": "Philadelphia",
        "confName": "East",
        "divName": "Atlantic",
        "primaryColor": "#006BB6",
        "secondaryColor": "#ED174C",
        "primaryLogoLocation": "assets/images/team_logos/76ers_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/76ers_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Phoenix",
        "altCityName": "Phoenix",
        "teamName": "Phoenix Suns",
        "tricode": "PHX",
        "teamId": 1610612756,
        "simpleName": "Suns",
        "urlName": "suns",
        "teamShortName": "Phoenix",
        "confName": "West",
        "divName": "Pacific",
        "primaryColor": "#1D1160",
        "secondaryColor": "#E56020",
        "primaryLogoLocation": "assets/images/team_logos/suns_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/suns_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Portland",
        "altCityName": "Portland",
        "teamName": "Portland Trail Blazers",
        "tricode": "POR",
        "teamId": 1610612757,
        "simpleName": "Trail Blazers",
        "urlName": "blazers",
        "teamShortName": "Portland",
        "confName": "West",
        "divName": "Northwest",
        "primaryColor": "#E03A3E",
        "secondaryColor": "#000000",
        "primaryLogoLocation": "assets/images/team_logos/trail_blazers_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/trail_blazers_secondary.gif"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Rio de Janeiro",
        "altCityName": "Rio de Janeiro",
        "teamName": "Rio de Janeiro Flamengo",
        "tricode": "FLA",
        "teamId": 12325,
        "simpleName": "Flamengo",
        "urlName": "flamengo",
        "teamShortName": "Flamengo",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Sacramento",
        "altCityName": "Sacramento",
        "teamName": "Sacramento Kings",
        "tricode": "SAC",
        "teamId": 1610612758,
        "simpleName": "Kings",
        "urlName": "kings",
        "teamShortName": "Sacramento",
        "confName": "West",
        "divName": "Pacific",
        "primaryColor": "#5A2D81",
        "secondaryColor": "#63727A",
        "primaryLogoLocation": "assets/images/team_logos/kings_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/kings_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "San Antonio",
        "altCityName": "San Antonio",
        "teamName": "San Antonio Spurs",
        "tricode": "SAS",
        "teamId": 1610612759,
        "simpleName": "Spurs",
        "urlName": "spurs",
        "teamShortName": "San Antonio",
        "confName": "West",
        "divName": "Southwest",
        "primaryColor": "#C4CED4",
        "secondaryColor": "#000000",
        "primaryLogoLocation": "assets/images/team_logos/spurs_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/spurs_secondary.gif"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Shanghai",
        "altCityName": "Shanghai",
        "teamName": "Shanghai Sharks",
        "tricode": "SDS",
        "teamId": 12329,
        "simpleName": "Sharks",
        "urlName": "shanghai_sharks",
        "teamShortName": "Shanghai",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": false,
        "isAllStar": false,
        "location": "Sydney",
        "altCityName": "Sydney",
        "teamName": "Sydney Kings",
        "tricode": "SYD",
        "teamId": 15015,
        "simpleName": "Kings",
        "urlName": "sydkings",
        "teamShortName": "Sydney",
        "confName": "Intl",
        "divName": ""
    },
    {
        "isNBAFranchise": false,
        "isAllStar": true,
        "location": "Team",
        "altCityName": "Team",
        "teamName": "All-Stars",
        "tricode": "EST",
        "teamId": 1699999999,
        "simpleName": "All-Stars",
        "urlName": "assn_away",
        "confName": "East",
        "divName": "East"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": true,
        "location": "Team",
        "altCityName": "Team",
        "teamName": "All-Stars",
        "tricode": "WST",
        "teamId": 1699999998,
        "simpleName": "All-Stars",
        "urlName": "assn_home",
        "confName": "West",
        "divName": "West"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": true,
        "location": "Team Giannis",
        "altCityName": "Team Giannis",
        "teamName": "Team Giannis",
        "tricode": "GNS",
        "teamId": 1610616833,
        "simpleName": "Team Giannis",
        "urlName": "team_giannis",
        "teamShortName": "Team Giannis",
        "confName": "East",
        "divName": "East",
        "primaryColor": "#C8102E",
        "secondaryColor": "#FFFFFF",
        "primaryLogoLocation": "assets/images/team_logos/team_giannis.svg",
        "secondaryLogoLocation": "assets/images/team_logos/team_giannis.svg"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": true,
        "location": "Team LeBron",
        "altCityName": "Team LeBron",
        "teamName": "Team LeBron",
        "tricode": "LBN",
        "teamId": 1610616834,
        "simpleName": "Team LeBron",
        "urlName": "team_lebron",
        "teamShortName": "Team LeBron",
        "confName": "West",
        "divName": "West",
        "primaryColor": "#1D428A",
        "secondaryColor": "#FFFFFF",
        "primaryLogoLocation": "assets/images/team_logos/team_lebron.svg",
        "secondaryLogoLocation": "assets/images/team_logos/team_lebron.svg"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Toronto",
        "altCityName": "Toronto",
        "teamName": "Toronto Raptors",
        "tricode": "TOR",
        "teamId": 1610612761,
        "simpleName": "Raptors",
        "urlName": "raptors",
        "teamShortName": "Toronto",
        "confName": "East",
        "divName": "Atlantic",
        "primaryColor": "#CE1141",
        "secondaryColor": "#000000",
        "primaryLogoLocation": "assets/images/team_logos/raptors_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/raptors_secondary.png"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": true,
        "location": "USA",
        "altCityName": "USA",
        "teamName": "USA",
        "tricode": "USA",
        "teamId": 1610616843,
        "simpleName": "USA",
        "urlName": "usa",
        "teamShortName": "USA",
        "confName": "East",
        "divName": "East",
        "primaryColor": "#FC4C02",
        "secondaryColor": "#FFFFFF",
        "primaryLogoLocation": "assets/images/team_logos/team_usa.svg",
        "secondaryLogoLocation": "assets/images/team_logos/team_usa.svg"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Utah",
        "altCityName": "Utah",
        "teamName": "Utah Jazz",
        "tricode": "UTA",
        "teamId": 1610612762,
        "simpleName": "Jazz",
        "urlName": "jazz",
        "teamShortName": "Utah",
        "confName": "West",
        "divName": "Northwest",
        "primaryColor": "#002B5C",
        "secondaryColor": "#F9A01B",
        "primaryLogoLocation": "assets/images/team_logos/jazz_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/jazz_secondary.png"
    },
    {
        "isNBAFranchise": true,
        "isAllStar": false,
        "location": "Washington",
        "altCityName": "Washington",
        "teamName": "Washington Wizards",
        "tricode": "WAS",
        "teamId": 1610612764,
        "simpleName": "Wizards",
        "urlName": "wizards",
        "teamShortName": "Washington",
        "confName": "East",
        "divName": "Southeast",
        "primaryColor": "#002B5C",
        "secondaryColor": "#E31837",
        "primaryLogoLocation": "assets/images/team_logos/wizards_primary.png",
        "secondaryLogoLocation": "assets/images/team_logos/wizards_secondary.png"
    },
    {
        "isNBAFranchise": false,
        "isAllStar": true,
        "location": "World",
        "altCityName": "World",
        "teamName": "World",
        "tricode": "WLD",
        "teamId": 1610616844,
        "simpleName": "World",
        "urlName": "world",
        "teamShortName": "World",
        "confName": "East",
        "divName": "East",
        "primaryColor": "#330072",
        "secondaryColor": "#FFFFFF",
        "primaryLogoLocation": "assets/images/team_logos/team_world.svg",
        "secondaryLogoLocation": "assets/images/team_logos/team_world.svg"
    }
]/*[
    {
      "teamId": 1610612737,
      "tricode": "ATL",
      "teamName": "Atlanta Hawks",
      "simpleName": "Hawks",
      "location": "Atlanta",
      "primaryColor": "#E03A3E",
      "secondaryColor": "#C1D32F",
      "primaryLogoLocation": "assets/images/team_logos/hawks_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/hawks_secondary.png"
    },
    {
      "teamId": 1610612738,
      "tricode": "BOS",
      "teamName": "Boston Celtics",
      "simpleName": "Celtics",
      "location": "Boston",
      "primaryColor": "#007A33",
      "secondaryColor": "#BA9653",
      "primaryLogoLocation": "assets/images/team_logos/celtics_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/celtics_secondary.png"
    },
    {
      "teamId": 1610612751,
      "tricode": "BKN",
      "teamName": "Brooklyn Nets",
      "simpleName": "Nets",
      "location": "Brooklyn",
      "primaryColor": "#000000",
      "secondaryColor": "#FFFFFF",
      "primaryLogoLocation": "assets/images/team_logos/nets_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/nets_secondary.png"
    },
    {
      "teamId": 1610612766,
      "tricode": "CHA",
      "teamName": "Charlotte Hornets",
      "simpleName": "Hornets",
      "location": "Charlotte",
      "primaryColor": "#1D1160",
      "secondaryColor": "#00788C",
      "primaryLogoLocation": "assets/images/team_logos/hornets_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/hornets_secondary.png"
    },
    {
      "teamId": 1610612741,
      "tricode": "CHI",
      "teamName": "Chicago Bulls",
      "simpleName": "Bulls",
      "location": "Chicago",
      "primaryColor": "#CE1141",
      "secondaryColor": "#000000",
      "primaryLogoLocation": "assets/images/team_logos/bulls_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/bulls_secondary.png"
    },
    {
      "teamId": 1610612739,
      "tricode": "CLE",
      "teamName": "Cleveland Cavaliers",
      "simpleName": "Cavaliers",
      "location": "Cleveland",
      "primaryColor": "#860038",
      "secondaryColor": "#FDBB30",
      "primaryLogoLocation": "assets/images/team_logos/cavaliers_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/cavaliers_secondary.png"
    },
    {
      "teamId": 1610612742,
      "tricode": "DAL",
      "teamName": "Dallas Mavericks",
      "simpleName": "Mavericks",
      "location": "Dallas",
      "primaryColor": "#00538C",
      "secondaryColor": "#B8C4CA",
      "primaryLogoLocation": "assets/images/team_logos/mavericks_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/mavericks_secondary.png"
    },
    {
      "teamId": 1610612743,
      "tricode": "DEN",
      "teamName": "Denver Nuggets",
      "simpleName": "Nuggets",
      "location": "Denver",
      "primaryColor": "#0E2240",
      "secondaryColor": "#FEC524",
      "primaryLogoLocation": "assets/images/team_logos/nuggets_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/nuggets_secondary.png"
    },
    {
      "teamId": 1610612765,
      "tricode": "DET",
      "teamName": "Detroit Pistons",
      "simpleName": "Pistons",
      "location": "Detroit",
      "primaryColor": "#C8102E",
      "secondaryColor": "#1D42BA",
      "primaryLogoLocation": "assets/images/team_logos/pistons_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/pistons_secondary.gif"
    },
    {
      "teamId": 1610612744,
      "tricode": "GSW",
      "teamName": "Golden State Warriors",
      "simpleName": "Warriors",
      "location": "Golden State",
      "primaryColor": "#1D428A",
      "secondaryColor": "#FFC72C",
      "primaryLogoLocation": "assets/images/team_logos/warriors_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/warriors_secondary.png"
    },
    {
      "teamId": 1610612745,
      "tricode": "HOU",
      "teamName": "Houston Rockets",
      "simpleName": "Rockets",
      "location": "Houston",
      "primaryColor": "#CE1141",
      "secondaryColor": "#C4CED4",
      "primaryLogoLocation": "assets/images/team_logos/rockets_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/rockets_secondary.png"
    },
    {
      "teamId": 1610612754,
      "tricode": "IND",
      "teamName": "Indiana Pacers",
      "simpleName": "Pacers",
      "location": "Indiana",
      "primaryColor": "#002D62",
      "secondaryColor": "#FDBB30",
      "primaryLogoLocation": "assets/images/team_logos/pacers_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/pacers_secondary.png"
    },
    {
      "teamId": 1610612746,
      "tricode": "LAC",
      "teamName": "Los Angeles Clippers",
      "simpleName": "Clippers",
      "location": "Los Angeles",
      "primaryColor": "#C8102E",
      "secondaryColor": "#1D428A",
      "primaryLogoLocation": "assets/images/team_logos/clippers_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/clippers_secondary.png"
    },
    {
      "teamId": 1610612747,
      "tricode": "LAL",
      "teamName": "Los Angeles Lakers",
      "simpleName": "Lakers",
      "location": "Los Angeles",
      "primaryColor": "#552583",
      "secondaryColor": "#FDB927",
      "primaryLogoLocation": "assets/images/team_logos/lakers_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/lakers_secondary.png"
    },
    {
      "teamId": 1610612763,
      "tricode": "MEM",
      "teamName": "Memphis Grizzlies",
      "simpleName": "Grizzlies",
      "location": "Memphis",
      "primaryColor": "#5D76A9",
      "secondaryColor": "#12173F",
      "primaryLogoLocation": "assets/images/team_logos/grizzlies_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/grizzlies_secondary.png"
    },
    {
      "teamId": 1610612748,
      "tricode": "MIA",
      "teamName": "Miami Heat",
      "simpleName": "Heat",
      "location": "Miami",
      "primaryColor": "#98002E",
      "secondaryColor": "#F9A01B",
      "primaryLogoLocation": "assets/images/team_logos/heat_primary.gif",
      "secondaryLogoLocation": "assets/images/team_logos/heat_secondary.png"
    },
    {
      "teamId": 1610612749,
      "tricode": "MIL",
      "teamName": "Milwaukee Bucks",
      "simpleName": "Bucks",
      "location": "Milwaukee",
      "primaryColor": "#00471B",
      "secondaryColor": "#EEE1C6",
      "primaryLogoLocation": "assets/images/team_logos/bucks_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/bucks_secondary.png"
    },
    {
      "teamId": 1610612750,
      "tricode": "MIN",
      "teamName": "Minnesota Timberwolves",
      "simpleName": "Timberwolves",
      "location": "Minnesota",
      "primaryColor": "#0C2340",
      "secondaryColor": "#9EA2A2",
      "primaryLogoLocation": "assets/images/team_logos/timberwolves_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/timberwolves_secondary.png"
    },
    {
      "teamId": 1610612740,
      "tricode": "NOP",
      "teamName": "New Orleans Pelicans",
      "simpleName": "Pelicans",
      "location": "New Orleans",
      "primaryColor": "#0C2340",
      "secondaryColor": "#85714D",
      "primaryLogoLocation": "assets/images/team_logos/pelicans_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/pelicans_secondary.png"
    },
    {
      "teamId": 1610612752,
      "tricode": "NYK",
      "teamName": "New York Knicks",
      "simpleName": "Knicks",
      "location": "New York",
      "primaryColor": "#006BB6",
      "secondaryColor": "#F58426",
      "primaryLogoLocation": "assets/images/team_logos/knicks_primary.gif",
      "secondaryLogoLocation": "assets/images/team_logos/knicks_secondary.png"
    },
    {
      "teamId": 1610612760,
      "tricode": "OKC",
      "teamName": "Oklahoma City Thunder",
      "simpleName": "Thunder",
      "location": "Oklahoma City",
      "primaryColor": "#007AC1",
      "secondaryColor": "#EF3B24",
      "primaryLogoLocation": "assets/images/team_logos/thunder_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/thunder_secondary.png"
    },
    {
      "teamId": 1610612753,
      "tricode": "ORL",
      "teamName": "Orlando Magic",
      "simpleName": "Magic",
      "location": "Orlando",
      "primaryColor": "#0077C0",
      "secondaryColor": "#C4CED4",
      "primaryLogoLocation": "assets/images/team_logos/magic_primary.gif",
      "secondaryLogoLocation": "assets/images/team_logos/magic_secondary.png"
    },
    {
      "teamId": 1610612755,
      "tricode": "PHI",
      "teamName": "Philadelphia 76ers",
      "simpleName": "76ers",
      "location": "Philadelphia",
      "primaryColor": "#006BB6",
      "secondaryColor": "#ED174C",
      "primaryLogoLocation": "assets/images/team_logos/76ers_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/76ers_secondary.png"
    },
    {
      "teamId": 1610612756,
      "tricode": "PHX",
      "teamName": "Phoenix Suns",
      "simpleName": "Suns",
      "location": "Phoenix",
      "primaryColor": "#1D1160",
      "secondaryColor": "#E56020",
      "primaryLogoLocation": "assets/images/team_logos/suns_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/suns_secondary.png"
    },
    {
      "teamId": 1610612757,
      "tricode": "POR",
      "teamName": "Portland Trail Blazers",
      "simpleName": "Trail Blazers",
      "location": "Portland",
      "primaryColor": "#E03A3E",
      "secondaryColor": "#000000",
      "primaryLogoLocation": "assets/images/team_logos/trail_blazers_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/trail_blazers_secondary.gif"
    },
    {
      "teamId": 1610612758,
      "tricode": "SAC",
      "teamName": "Sacramento Kings",
      "simpleName": "Kings",
      "location": "Sacramento",
      "primaryColor": "#5A2D81",
      "secondaryColor": "#63727A",
      "primaryLogoLocation": "assets/images/team_logos/kings_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/kings_secondary.png"
    },
    {
      "teamId": 1610612759,
      "tricode": "SAS",
      "teamName": "San Antonio Spurs",
      "simpleName": "Spurs",
      "location": "San Antonio",
      "primaryColor": "#C4CED4",
      "secondaryColor": "#000000",
      "primaryLogoLocation": "assets/images/team_logos/spurs_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/spurs_secondary.gif"
    },
    {
      "teamId": 1610612761,
      "tricode": "TOR",
      "teamName": "Toronto Raptors",
      "simpleName": "Raptors",
      "location": "Toronto",
      "primaryColor": "#CE1141",
      "secondaryColor": "#000000",
      "primaryLogoLocation": "assets/images/team_logos/raptors_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/raptors_secondary.png"
    },
    {
      "teamId": 1610612762,
      "tricode": "UTA",
      "teamName": "Utah Jazz",
      "simpleName": "Jazz",
      "location": "Utah",
      "primaryColor": "#002B5C",
      "secondaryColor": "#F9A01B",
      "primaryLogoLocation": "assets/images/team_logos/jazz_primary.png",
      "secondaryLogoLocation": "assets/images/team_logos/jazz_secondary.png"
    },
    {
      "teamId": 1610612764,
      "tricode": "WAS",
      "teamName": "Washington Wizards",
      "simpleName": "Wizards",
      "location": "Washington",
      "primaryColor": "#002B5C",
      "secondaryColor": "#E31837",
      "primaryLogoLocation": "assets/images/team_logos/wizards_primary.gif",
      "secondaryLogoLocation": "assets/images/team_logos/wizards_secondary.png"
    }
  ]*/
}